// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;

	public partial struct VideoGLTextureUploadMeta : IEquatable<VideoGLTextureUploadMeta> {

		public bool Equals(VideoGLTextureUploadMeta other)
		{
			return this.GetHashCode() == other.GetHashCode();
		}

	}
}
