<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>GLibSharp is a C# wrapper for the GLib library.</Description>
    <PackageTags>glib;glibsharp;glib-sharp;wrapper</PackageTags>
    <AssemblyVersion>3.24.24.1</AssemblyVersion>
    <FileVersion>3.24.24.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

</Project>
